### ISSUE TITLE
Environment Library Management 

### ISSUE THREAD

**Issue by LuluW8071** [bhandariarun/NEPSE_ANALYSIS#3]
It is better to add `requirements.txt` and put `venv` library folder on `.gitignore` file as environment contains many dependencies that may exceed 1GB 

To get `requirements.txt` just enter the command:
```bash
pip freeze > requirements.txt
```

This will generate all the library dependencies name with their versions present on the environment in `.txt` file. And, to install the requirements in your environment (if it doesn't exist make one: `py -m venv env`), activate the environment and enter the command: 
```bash
pip install -r requirements.txt
```

**Comment by bhandariarun** [comment]
Thanks for you suggestion. It means a lot
